//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticket_Vendor_Machine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FareStep
    {
        public int StepID { get; set; }
        public int FromStationCount { get; set; }
        public int ToStationCount { get; set; }
        public decimal CashPrice { get; set; }
        public decimal NonCashPrice { get; set; }
    }
}
